--zad1
drop table  T_RANGE;

CREATE TABLE T_RANGE (
    id NUMBER,
    data VARCHAR2(100)
)
PARTITION BY RANGE (id) (
    PARTITION p1 VALUES LESS THAN (1000),
    PARTITION p2 VALUES LESS THAN (2000),
    PARTITION p3 VALUES LESS THAN (MAXVALUE)
);

--zad2
drop table T_INTERVAL;
CREATE TABLE T_INTERVAL (
    id NUMBER,
    event_date DATE
)
PARTITION BY RANGE (event_date)
INTERVAL (INTERVAL '1' MONTH) (
    PARTITION p_start VALUES LESS THAN (DATE '2024-01-01')
);


--zad3
drop table T_HASH;
CREATE TABLE T_HASH (
    id VARCHAR2(100),
    value NUMBER
)
PARTITION BY HASH (id)
PARTITIONS 4;


--zad4

CREATE TABLE T_LIST (
    id CHAR(2),
    description VARCHAR2(100)
)
PARTITION BY LIST (id) (
    PARTITION p_region1 VALUES ('RU', 'BY', 'UA'),
    PARTITION p_region2 VALUES ('US', 'CA'),
    PARTITION p_other VALUES (DEFAULT)
);


--zad5

INSERT INTO T_RANGE (id, data) VALUES (500, 'Data for p1');
INSERT INTO T_RANGE (id, data) VALUES (1500, 'Data for p2');
INSERT INTO T_RANGE (id, data) VALUES (2500, 'Data for p3');

-- Проверяем секционирование
SELECT * FROM T_RANGE PARTITION (p1);
SELECT * FROM T_RANGE PARTITION (p2);
SELECT * FROM T_RANGE PARTITION (p3);

INSERT INTO T_INTERVAL (id, event_date) VALUES (1, DATE '2023-11-15');  
INSERT INTO T_INTERVAL (id, event_date) VALUES (2, DATE '2024-01-05');  
INSERT INTO T_INTERVAL (id, event_date) VALUES (3, DATE '2024-02-10');  

-- Проверяем секционирование
SELECT * FROM T_INTERVAL PARTITION FOR (DATE '2023-11-15');
SELECT * FROM T_INTERVAL PARTITION FOR (DATE '2024-01-05');
SELECT * FROM T_INTERVAL PARTITION FOR (DATE '2024-02-10');


INSERT INTO T_HASH (id, value) VALUES ('ID1', 100);  
INSERT INTO T_HASH (id, value) VALUES ('ID10', 200);  
INSERT INTO T_HASH (id, value) VALUES ('ID3', 300); 
INSERT INTO T_HASH (id, value) VALUES ('ID4', 400); 

SELECT PARTITION_NAME, TABLE_NAME
FROM USER_TAB_PARTITIONS
WHERE TABLE_NAME = 'T_HASH';

-- Проверяем секционирование
SELECT * FROM T_HASH PARTITION (SYS_P652);
SELECT * FROM T_HASH PARTITION (SYS_P653);
SELECT * FROM T_HASH PARTITION (SYS_P654);
SELECT * FROM T_HASH PARTITION (SYS_P655);
select * from T_HASH;

INSERT INTO T_LIST (id, description) VALUES ('RU', 'Data for Russia');
INSERT INTO T_LIST (id, description) VALUES ('US', 'Data for USA');
INSERT INTO T_LIST (id, description) VALUES ('CA', 'Data for Canada');
INSERT INTO T_LIST (id, description) VALUES ('JP', 'Data for Japan');

-- Проверяем секционирование
SELECT * FROM T_LIST PARTITION (P_REGION1);
SELECT * FROM T_LIST PARTITION (P_REGION2);
SELECT * FROM T_LIST PARTITION (P_OTHER);
SELECT * FROM T_LIST;
--zad6
-- Копируем строку с новым значением ключа в нужную секцию
INSERT INTO T_RANGE (id, data)
SELECT 1500, data FROM T_RANGE WHERE id = 500;

DELETE FROM T_RANGE WHERE id = 500;

alter table T_RANGE enable row movement;

SELECT * FROM T_RANGE PARTITION (p1);
SELECT * FROM T_RANGE PARTITION (p2);
SELECT * FROM T_RANGE PARTITION (p3);

UPDATE T_RANGE 
SET id = 1500
WHERE id = 500;


SELECT * FROM T_RANGE;
alter table T_INTERVAL enable row movement;

UPDATE T_INTERVAL 
SET event_date = DATE '2024-02-05'
WHERE id = 2;


SELECT * FROM T_INTERVAL PARTITION FOR (DATE '2023-11-15');
SELECT * FROM T_INTERVAL PARTITION FOR (DATE '2024-01-05');
SELECT * FROM T_INTERVAL PARTITION FOR (DATE '2024-02-10');


alter table T_HASH enable row movement;

UPDATE T_HASH 
SET id = 'ID10'
WHERE id = 'ID0';


SELECT * FROM T_HASH PARTITION (SYS_P652);
SELECT * FROM T_HASH PARTITION (SYS_P653);
SELECT * FROM T_HASH PARTITION (SYS_P654);
SELECT * FROM T_HASH PARTITION (SYS_P655);

SELECT * FROM T_HASH;


SELECT * FROM T_LIST PARTITION (P_REGION1);
SELECT * FROM T_LIST PARTITION (P_REGION2);
SELECT * FROM T_LIST PARTITION (P_OTHER);


alter table T_LIST enable row movement;

UPDATE T_LIST 
SET id = 'US'
WHERE id = 'RU';
--zad7

-- Сначала проверим содержимое секций
SELECT * FROM T_RANGE PARTITION (P1);
SELECT * FROM T_RANGE PARTITION (P2);

-- Объединяем секции p1 и p2 в одну
ALTER TABLE T_RANGE MERGE PARTITIONS p1, p2 INTO PARTITION p1_p2;

-- Проверяем новое содержимое объединенной секции
SELECT * FROM T_RANGE PARTITION (P1_P2);


--zad8
-- Проверяем содержимое секции p3
SELECT * FROM T_RANGE PARTITION (P3);
INSERT INTO T_RANGE (id, data) VALUES (3500, 'Data for p3');

-- Разделяем секцию p3
ALTER TABLE T_RANGE SPLIT PARTITION p3 AT (3000)
INTO (
    PARTITION p3a,
    PARTITION p3b
);

-- Проверяем содержимое новых секций
SELECT * FROM T_RANGE PARTITION (P3A);
SELECT * FROM T_RANGE PARTITION (P3B);


--zad9
drop table TEMP_LIST;
CREATE TABLE TEMP_LIST AS
SELECT * FROM T_LIST WHERE 1=0;

SELECT * FROM T_LIST PARTITION (P_REGION2);

ALTER TABLE T_LIST EXCHANGE PARTITION P_REGION2 WITH TABLE TEMP_LIST;

SELECT * FROM TEMP_LIST;

SELECT * FROM T_LIST PARTITION (P_REGION2);
